# Generated by Django 3.1.1 on 2020-09-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_num', models.IntegerField()),
                ('round', models.CharField(choices=[('Round 1', '1'), ('Round 2', '2'), ('Round 3', '3'), ('Pre-Quarter', 'Pre-Qua'), ('Quarter', 'Quarter'), ('Semi-Final', 'Semi'), ('Final', 'Final')], default='1', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('collge', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=120)),
                ('goal', models.IntegerField(default=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='scorecard.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='t2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='scorecard.team'),
        ),
    ]
